package com.test.gank.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.test.gank.model.GankItem;

import com.test.gank.db.GankItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gankItemDaoConfig;

    private final GankItemDao gankItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gankItemDaoConfig = daoConfigMap.get(GankItemDao.class).clone();
        gankItemDaoConfig.initIdentityScope(type);

        gankItemDao = new GankItemDao(gankItemDaoConfig, this);

        registerDao(GankItem.class, gankItemDao);
    }
    
    public void clear() {
        gankItemDaoConfig.clearIdentityScope();
    }

    public GankItemDao getGankItemDao() {
        return gankItemDao;
    }

}
