package com.test.gank.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import com.test.gank.model.GankItem;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GANK_ITEM".
*/
public class GankItemDao extends AbstractDao<GankItem, Long> {

    public static final String TABLENAME = "GANK_ITEM";

    /**
     * Properties of entity GankItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property DbId = new Property(0, Long.class, "DbId", true, "_id");
        public final static Property GankID = new Property(1, String.class, "gankID", false, "GANK_ID");
        public final static Property CreatedAt = new Property(2, String.class, "createdAt", false, "CREATED_AT");
        public final static Property Desc = new Property(3, String.class, "desc", false, "DESC");
        public final static Property PublishedAt = new Property(4, Long.class, "publishedAt", false, "PUBLISHED_AT");
        public final static Property Source = new Property(5, String.class, "source", false, "SOURCE");
        public final static Property Type = new Property(6, String.class, "type", false, "TYPE");
        public final static Property Url = new Property(7, String.class, "url", false, "URL");
        public final static Property Used = new Property(8, boolean.class, "used", false, "USED");
        public final static Property Who = new Property(9, String.class, "who", false, "WHO");
        public final static Property Images = new Property(10, String.class, "images", false, "IMAGES");
    }

    private final DateConverter publishedAtConverter = new DateConverter();
    private final StringConverter imagesConverter = new StringConverter();

    public GankItemDao(DaoConfig config) {
        super(config);
    }
    
    public GankItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GANK_ITEM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: DbId
                "\"GANK_ID\" TEXT UNIQUE ," + // 1: gankID
                "\"CREATED_AT\" TEXT," + // 2: createdAt
                "\"DESC\" TEXT," + // 3: desc
                "\"PUBLISHED_AT\" INTEGER," + // 4: publishedAt
                "\"SOURCE\" TEXT," + // 5: source
                "\"TYPE\" TEXT," + // 6: type
                "\"URL\" TEXT," + // 7: url
                "\"USED\" INTEGER NOT NULL ," + // 8: used
                "\"WHO\" TEXT," + // 9: who
                "\"IMAGES\" TEXT);"); // 10: images
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GANK_ITEM\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GankItem entity) {
        stmt.clearBindings();
 
        Long DbId = entity.getDbId();
        if (DbId != null) {
            stmt.bindLong(1, DbId);
        }
 
        String gankID = entity.getGankID();
        if (gankID != null) {
            stmt.bindString(2, gankID);
        }
 
        String createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindString(3, createdAt);
        }
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(4, desc);
        }
 
        String publishedAt = entity.getPublishedAt();
        if (publishedAt != null) {
            stmt.bindLong(5, publishedAtConverter.convertToDatabaseValue(publishedAt));
        }
 
        String source = entity.getSource();
        if (source != null) {
            stmt.bindString(6, source);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(7, type);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(8, url);
        }
        stmt.bindLong(9, entity.getUsed() ? 1L: 0L);
 
        String who = entity.getWho();
        if (who != null) {
            stmt.bindString(10, who);
        }
 
        List images = entity.getImages();
        if (images != null) {
            stmt.bindString(11, imagesConverter.convertToDatabaseValue(images));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GankItem entity) {
        stmt.clearBindings();
 
        Long DbId = entity.getDbId();
        if (DbId != null) {
            stmt.bindLong(1, DbId);
        }
 
        String gankID = entity.getGankID();
        if (gankID != null) {
            stmt.bindString(2, gankID);
        }
 
        String createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindString(3, createdAt);
        }
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(4, desc);
        }
 
        String publishedAt = entity.getPublishedAt();
        if (publishedAt != null) {
            stmt.bindLong(5, publishedAtConverter.convertToDatabaseValue(publishedAt));
        }
 
        String source = entity.getSource();
        if (source != null) {
            stmt.bindString(6, source);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(7, type);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(8, url);
        }
        stmt.bindLong(9, entity.getUsed() ? 1L: 0L);
 
        String who = entity.getWho();
        if (who != null) {
            stmt.bindString(10, who);
        }
 
        List images = entity.getImages();
        if (images != null) {
            stmt.bindString(11, imagesConverter.convertToDatabaseValue(images));
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GankItem readEntity(Cursor cursor, int offset) {
        GankItem entity = new GankItem( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // DbId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // gankID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // createdAt
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // desc
            cursor.isNull(offset + 4) ? null : publishedAtConverter.convertToEntityProperty(cursor.getLong(offset + 4)), // publishedAt
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // source
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // type
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // url
            cursor.getShort(offset + 8) != 0, // used
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // who
            cursor.isNull(offset + 10) ? null : imagesConverter.convertToEntityProperty(cursor.getString(offset + 10)) // images
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GankItem entity, int offset) {
        entity.setDbId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setGankID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCreatedAt(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDesc(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPublishedAt(cursor.isNull(offset + 4) ? null : publishedAtConverter.convertToEntityProperty(cursor.getLong(offset + 4)));
        entity.setSource(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setType(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setUrl(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setUsed(cursor.getShort(offset + 8) != 0);
        entity.setWho(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setImages(cursor.isNull(offset + 10) ? null : imagesConverter.convertToEntityProperty(cursor.getString(offset + 10)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GankItem entity, long rowId) {
        entity.setDbId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GankItem entity) {
        if(entity != null) {
            return entity.getDbId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GankItem entity) {
        return entity.getDbId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
